### PR TITLE
Add `.show()` and `.hide()` methods to Controller

### PR DESCRIPTION
**Pull request by Peque**
Closes https://github.com/georgealways/lil-gui/issues/54.

### CODE REVIEW

**Comment by Peque** [comment]
@georgealways Apart from the tests, I'd like to try it locally. I've tried with:

```
npm install git+ssh://git@github.com:Peque/lil-gui.git#<commit-hash>
```

Which successfully runs the command, but then I get a `Module not found: Error: Can't resolve 'lil-gui' in '<path>/lib'`.

How should I install the package from a remote source repository? Or, if it can be done by building the package locally first, how to install the locally-built package as a dependency?

**Comment by georgealways** [comment]
Hey, this is looking great. If you want to try importing it into a different package for testing, I think `npm link` is good for that.

**Comment by Peque** [comment]
@georgealways It was already enabled:

Screenshot from 2022-05-31 23-24-06

If you are unable to push changes, feel free to open a new PR with your changes amended and close this one. Or just add a comment with the required changes and I'll be happy to implement them. Whatever works best for you, I don't mind. :blush:

**Comment by georgealways** [comment]
Thank you! Hadn't tried to push myself yet, just wanted to double check that it was enabled. 

I may just try and make the JSDoc for `gui/controller.show()` shorter now that it appears twice. 

In the past I've been tempted to make Controller and GUI inherit from a single base class for methods like these, but I don't think there's enough to justify the abstraction. 

Appreciate it!

**Comment by georgealways** [comment]
Excuse the noise, tried using the `gh` command line tool to merge this and it decided to bring the changes into master.

**Pull request merged**
