### PR TITLE
Multi-touch

### PR DESCRIPTION
**Pull request by xinaesthete**
As per #76.

Quick hack, seems to be fairly much working, although could probably clean up (eg left some commented code hanging around, moved around where `e.preventDefault()` is called).

Change to simulateDrag seems to keep the test runner happy.

### CODE REVIEW

**Comment by xinaesthete** [comment]
Might be able to hang on to a reference to the touch itself, which might be cleaner.

**Comment by georgealways** [comment]
Hey this is great! Thanks so much for running the linter / updating the tests, etc.

So I had a try at this myself. It's pretty much identical to what you've got, except for the way I'm rejecting multiple touches on the same slider and some stylistic things.

https://github.com/georgealways/lil-gui/compare/dev...slider-multi-touch?expand=1#diff-5624150e083142352c01694acdf7d2ca00c1adf1f0c0e0bce0fcedd1b97670d5

I didn't have a chance to test exhaustively (`examples/kitchen-sink` has a lot of sliders) or to make sure everything is working in `examples/touch-scroll-tests`. Would love your help with that!

If you want, let's make a new PR off of the `dev` branch with the changes from my branch above, so that you get credit if we merge this. Nice work!

**Comment by xinaesthete** [comment]
Yours does indeed look pretty similar, probably slightly better for how to reject multiple touches; this bit from `onTouchStart`

```js
if ( activeTouchID !== undefined ) return;
```

makes good sense.

I've tested mine a bit now with something that has lots of programmatically generated sliders in different panels / nested folders and I think it seems fine.

Makes sense to try to cover a couple of different test cases I suppose, I'm not all that much in the habbit of writing tests but it might be good practice.

Kind of you to consider making it so I get some credit, I don't contribute as much as I might to open-source so it'd be nice to have something like this be counted.

**Comment by xinaesthete** [comment]
I got a bit thrown for a minute by the `decimals` sliders syncing with each-other in `kitchen-sink` :)

**Comment by xinaesthete** [comment]
One thing that can lead to not totally ideal behaviour is when there's a mouse or touch event on something that's already being dragged. In fact, I have one slider in the `kitchen-sink` instance I have running now that has got itself into a state where it no longer responds having once suffered the trauma of this abuse.

**Comment by xinaesthete** [comment]
It must somehow be possible for a touch to end without getting through `onTouchEnd` in the expected way, so `activeTouchID = undefined;` doesn't happen and from that point on the slider will always ignore `onTouchStart`.

**Pull request closed without merging**
