### PR TITLE
Remove side effect false alarm

### PR DESCRIPTION
**Pull request by jakelazaroff**
I'm using lil-gui in an app bundled with [esbuild](https://esbuild.github.io). It works great, except when I bundle for production esbuild isn't able to fully tree shake away lil-gui. There are two fixes for that, both of which I've included in this PR:

1. Add `"sideEffects": false` to `package.json`, which tells esbuild to ignore any potential side effects. (This isn't an esbuild-specific feature; [Webpack supports this too](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free).)
2. In `src/utils/getColorFormat.js`, wrap `ARRAY.match: Array.isArray` in a function. [esbuild considers using `Array.isArray` directly a potential side effect](https://esbuild.github.io/api/#tree-shaking-and-side-effects), since property access could technically run code in a getter.

Either/both of these will work; I'd prefer at least the second solution, since tools like esbuild also provide the option to ignore annotations like `"sideEffects": false`.

### CODE REVIEW

**Comment by georgealways** [comment]
Hey—thanks for this, I wasn't familiar with esbuild.

So of the two approaches, I'd opt for number 1. It basically seems to me like a guarantee in the package.json that the library won't be modifying any globals, and that's definitely the intent.

If I understand Option 2, it seems like there's some sort of side-effect analysis tool that isn't happy with that bare reference to `Array.isArray`. But I don't quite understand how that could introduce side-effects, or how wrapping it in an arrow function would mitigate anything if it did. Could you explain that a bit more?

In general, I'm not crazy about modifying code to satisfy that tool, but if we can get by with the "you have my word" approach of `sideEffects: false` then I'm happy to do that.

**Comment by jakelazaroff** [comment]
Because getters can run arbitrary code, property access can cause side effects. Here's a (contrived) example of what it's worried about:

```js
const oldIsArray = Array.isArray;

Object.defineProperty(Array, "isArray", {
  get() {
    console.log("side effect!");
    return (value) => oldIsArray(value);
  }
});

Array.isArray; // console prints "side effect!" even though the function isn't called
```

Obviously, lil-gui isn't doing anything of the sort. But esbuild isn't doing any sort of deep static analysis, it just sees that there's property access and flags it as potentially effectful. Wrapping it in a function fixes this because the property access happens later when the function is called, rather than immediately when the module is imported.

The reason I prefer that solution is that the guarantee can technically be broken — if you accidentally introduce a side effect in future, or intentionally add one and forget to remove the `package.json` property, then the library will potentially be tree shaken when it actually needs to be included to prevent a bug (whereas the current situation is that it just makes the bundle size a little bigger). In all honesty, that seems unlikely — this is a pretty esoteric corner case — but it is a thing. I did try to make the code match the style of the `OBJECT.match` function in the same file, if that makes a difference.

Anyway: your library, your decision! Either one would solve the issue, so I'm really just splitting hairs here.

**Comment by jakelazaroff** [comment]
For posterity, I decided to try this with webpack too, just to show that this behavior isn't idiosyncratic to esbuild. I added a test case in [this gist](https://gist.github.com/jakelazaroff/86c0970c4acaeeb3d4fd6f440c58ea2b) — basically, a tiny app that imports lil-gui but doesn't actually use it. Running `npm run build` results in the following output file:

```js
(()=>{"use strict";Array.isArray,console.log("Hello, world!")})();
```

Better than esbuild (which includes the entire `INT` and `ARRAY` objects from `src/utils/getColorFormat.js`) but still: 13 bytes that don't need to be there. Making either of the changes in this PR causes webpack to drop `Array.isArray` from the output as well.

**Comment by georgealways** [comment]
Got it, got it—thanks for explaining. If I understand: it's just upset that `Array.isArray` is "evaluated" on import, it doesn't care if it gets called later. 

So let's do both like you have it now: the package.json and the arrow function wrapper. But **do you know of a way to have this side-effect check run in our prepublish task**? I could see myself forgetting why the arrow function is there and "optimizing" ;)

**Comment by jakelazaroff** [comment]
Yes, that's correct! As for having a check run on pre-publish, I'm not sure 😅 I found [this package](https://www.npmjs.com/package/check-side-effects)[](https://www.npmjs.com/package/check-side-effects), but it's not super popular and hasn't been updated in two years.

**Comment by georgealways** [comment]
Okay, we'll have to make do with a reminder comment. And in the meantime I guess you'll just have to be that script for me ;)

**Comment by jakelazaroff** [comment]
Sounds good haha, I'll make sure to let you know if I notice it sneaking back into my production bundle 🙂

**Comment by georgealways** [comment]
That's in and published for 0.18 — thanks for the help!

**Pull request merged**
